export enum NODO {
  ENV_CHECKLIST_ARRANQUE_MAQUINA = 1202,
  ENV_CHECKLIST_ARRANQUE_ENVASADO = 1203,
  FRI_REGISTRO_EVALUACION_ATRIBUTOS = 1205,
  FRI_CHECKLIST_ARRANQUE_LINEA_MANUFACTURA = 1206,
  SAZ_CHECKLIST_ARRANQUE = 1208,
  ENV_GRANEL_CHECKLIST = 1210,
  ENV_GRANEL_CONTROL_PARÁMETROS = 1211,
  ENV_GRANEL_EVALUACIÓN_PT = 1212,
  ENV_GRANEL_CODIFICACIÓN_CAJA = 1213,
  ENV_BLENDING_CHECKLIST = 1214,
  ENV_BLENDING_CONTROL = 1215,
  ACO_CHECKLIST_ARRANQUE_MAIZ = 1217,
  ACO_CONTROL_PELADO_REMOJO_Y_SANCOCHADO_MAIZ = 1218,
  ACO_CONTROL_REMOJO_HABAS_REPOSO_MAIZ = 1219,
  ACO_CONTROL_PEF = 1224,
}

export const ACCION_ENV_CHECKLIST_ARRANQUE_MAQUINA = {
  LECTURA: 'ENV01LE',
  ESCRITURA: 'ENV01ES',
  REVISION: 'ENV01RE',
};

export const ACCION_ENV_CHECKLIST_ARRANQUE_ENVASADO = {
  LECTURA: 'ENV02LE',
  ESCRITURA: 'ENV02ES',
  REVISION: 'ENV02RE',
};

export const ACCION_ENV_REGISTRO_PEDACERIA = {
  LECTURA: 'ENV03LE',
  ESCRITURA: 'ENV03ES',
  REVISION: 'ENV03RE',
};

export const ACCION_FR_REGISTRO_EVALUACION_ATRIBUTOS = {
  LECTURA: 'FRI01LE',
  ESCRITURA: 'FRI01ES',
  REVISION: 'FRI01RE',
};

export const ACCION_FR_CHECKLIST_ARRANQUE_MANUFACTURA = {
  LECTURA: 'FRI02LE',
  ESCRITURA: 'FRI02ES',
  REVISION: 'FRI02RE',
};

export const ACCION_FR_CARACTERIZACION_PRODUCTO = {
  LECTURA: 'FRI03LE',
  ESCRITURA: 'FRI03ES',
  REVISION: 'FRI03RE',
};

export const ACCION_FR_CONTROL_ACEITE = {
  LECTURA: 'FRI04LE',
  ESCRITURA: 'FRI04ES',
  REVISION: 'FRI04RE',
};

export const ACCION_SAZ_CHECKLIST_ARRANQUE = {
  LECTURA: 'SAZ01LE',
  ESCRITURA: 'SAZ01ES',
  REVISION: 'SAZ01RE',
};

export const ACCION_ENV_GRANEL_CHECKLIST = {
  LECTURA: 'ENG01LE',
  ESCRITURA: 'ENG01ES',
  REVISION: 'ENG01RE',
};

export const ACCION_ENV_GRANEL_CONTROL_PARAMETROS = {
  LECTURA: 'ENG02LE',
  ESCRITURA: 'ENG02ES',
  REVISION: 'ENG02RE',
};

export const ACCION_ENV_GRANEL_EVALUACION_PT = {
  LECTURA: 'ENG03LE',
  ESCRITURA: 'ENG03ES',
  REVISION: 'ENG03RE',
};

export const ACCION_ENV_GRANEL_CODIFICACION_CAJA = {
  LECTURA: 'ENG04LE',
  ESCRITURA: 'ENG04ES',
  REVISION: 'ENG04RE',
};

export const ACCION_ENV_BLENDING_CHECKLIST = {
  LECTURA: 'BLE01LE',
  ESCRITURA: 'BLE01ES',
  REVISION: 'BLE01RE',
};

export const ACCION_ENV_BLENDING_CONTROL = {
  LECTURA: 'BLE02LE',
  ESCRITURA: 'BLE02ES',
  REVISION: 'BLE02RE',
};

export const ACCION_ACO_CHECKLIST_ARRANQUE_MAIZ = {
  LECTURA: 'ACO01LE',
  ESCRITURA: 'ACO01ES',
  REVISION: 'ACO01RE',
};

export const ACCION_ACO_CONTROL_PELADO_REMOJO_SANCOCHADO_MAIZ = {
  LECTURA: 'ACO02LE',
  ESCRITURA: 'ACO02ES',
  REVISION: 'ACO02RE',
};

export const ACCION_ACO_CONTROL_REMOJO_HABAS_REPOSO_MAIZ = {
  LECTURA: 'ACO03LE',
  ESCRITURA: 'ACO03ES',
  REVISION: 'ACO03RE',
};

export const ACCION_ACO_CHECKLIST_LAVADO_TUBERCULO = {
  LECTURA: 'ACO05LE',
  ESCRITURA: 'ACO05ES',
  REVISION: 'ACO05RE',
};

export const ACCION_ACO_CONTROL_RAYOS_X = {
  LECTURA: 'ACO09LE',
  ESCRITURA: 'ACO09ES',
  REVISION: 'ACO09RE',
};

export const ACCION_ACO_CONTROL_PEF = {
  LECTURA: 'ACO10LE',
  ESCRITURA: 'ACO10ES',
  REVISION: 'ACO10RE',
};
