//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credencial", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    public partial class Credencial : object
    {
        
        private string AnexoField;
        
        private string CelularField;
        
        private string ContraseñaField;
        
        private string CorreoField;
        
        private int CredencialIdField;
        
        private string DepartamentoField;
        
        private string DepartamentoDescField;
        
        private string EmpleadoField;
        
        private System.DateTime FechaBloqueoField;
        
        private bool FlgBloqueoField;
        
        private bool FlgSesionAliasField;
        
        private string NombrePersonalField;
        
        private string PuestoField;
        
        private string PuestoDescField;
        
        private ServiceReference.Sede SedeField;
        
        private int SedeIdField;
        
        private string UsuarioField;
        
        private string UsuarioAliasField;
        
        private string UsuarioRedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anexo
        {
            get
            {
                return this.AnexoField;
            }
            set
            {
                this.AnexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular
        {
            get
            {
                return this.CelularField;
            }
            set
            {
                this.CelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña
        {
            get
            {
                return this.ContraseñaField;
            }
            set
            {
                this.ContraseñaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CredencialId
        {
            get
            {
                return this.CredencialIdField;
            }
            set
            {
                this.CredencialIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoDesc
        {
            get
            {
                return this.DepartamentoDescField;
            }
            set
            {
                this.DepartamentoDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empleado
        {
            get
            {
                return this.EmpleadoField;
            }
            set
            {
                this.EmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaBloqueo
        {
            get
            {
                return this.FechaBloqueoField;
            }
            set
            {
                this.FechaBloqueoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgBloqueo
        {
            get
            {
                return this.FlgBloqueoField;
            }
            set
            {
                this.FlgBloqueoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgSesionAlias
        {
            get
            {
                return this.FlgSesionAliasField;
            }
            set
            {
                this.FlgSesionAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePersonal
        {
            get
            {
                return this.NombrePersonalField;
            }
            set
            {
                this.NombrePersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Puesto
        {
            get
            {
                return this.PuestoField;
            }
            set
            {
                this.PuestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PuestoDesc
        {
            get
            {
                return this.PuestoDescField;
            }
            set
            {
                this.PuestoDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Sede Sede
        {
            get
            {
                return this.SedeField;
            }
            set
            {
                this.SedeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SedeId
        {
            get
            {
                return this.SedeIdField;
            }
            set
            {
                this.SedeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioAlias
        {
            get
            {
                return this.UsuarioAliasField;
            }
            set
            {
                this.UsuarioAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioRed
        {
            get
            {
                return this.UsuarioRedField;
            }
            set
            {
                this.UsuarioRedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    public partial class Sede : object
    {
        
        private int DireccionField;
        
        private ServiceReference.Empresa EmpresaField;
        
        private int EmpresaIdField;
        
        private int InicialSedeField;
        
        private int NombreSedeField;
        
        private int SedeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId
        {
            get
            {
                return this.EmpresaIdField;
            }
            set
            {
                this.EmpresaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InicialSede
        {
            get
            {
                return this.InicialSedeField;
            }
            set
            {
                this.InicialSedeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NombreSede
        {
            get
            {
                return this.NombreSedeField;
            }
            set
            {
                this.NombreSedeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SedeId
        {
            get
            {
                return this.SedeIdField;
            }
            set
            {
                this.SedeIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    public partial class Empresa : object
    {
        
        private string AbrevEmpresaField;
        
        private int EmpresaIdField;
        
        private bool EsEntidadField;
        
        private string ImgLogoField;
        
        private string NombreComercialField;
        
        private string NroRucField;
        
        private string RazonSocialField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbrevEmpresa
        {
            get
            {
                return this.AbrevEmpresaField;
            }
            set
            {
                this.AbrevEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId
        {
            get
            {
                return this.EmpresaIdField;
            }
            set
            {
                this.EmpresaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsEntidad
        {
            get
            {
                return this.EsEntidadField;
            }
            set
            {
                this.EsEntidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImgLogo
        {
            get
            {
                return this.ImgLogoField;
            }
            set
            {
                this.ImgLogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial
        {
            get
            {
                return this.NombreComercialField;
            }
            set
            {
                this.NombreComercialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroRuc
        {
            get
            {
                return this.NroRucField;
            }
            set
            {
                this.NroRucField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nodo", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    public partial class Nodo : object
    {
        
        private string DescripcionField;
        
        private bool EsEstandarField;
        
        private bool FlgIntegradoField;
        
        private string IconoField;
        
        private int NodoIdField;
        
        private int NodoPadreField;
        
        private string NombreField;
        
        private int OrdenField;
        
        private ServiceReference.Software SoftwareField;
        
        private int SoftwareIdField;
        
        private int TipoNodoIdField;
        
        private string UbicacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsEstandar
        {
            get
            {
                return this.EsEstandarField;
            }
            set
            {
                this.EsEstandarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FlgIntegrado
        {
            get
            {
                return this.FlgIntegradoField;
            }
            set
            {
                this.FlgIntegradoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icono
        {
            get
            {
                return this.IconoField;
            }
            set
            {
                this.IconoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NodoId
        {
            get
            {
                return this.NodoIdField;
            }
            set
            {
                this.NodoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NodoPadre
        {
            get
            {
                return this.NodoPadreField;
            }
            set
            {
                this.NodoPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden
        {
            get
            {
                return this.OrdenField;
            }
            set
            {
                this.OrdenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Software Software
        {
            get
            {
                return this.SoftwareField;
            }
            set
            {
                this.SoftwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoftwareId
        {
            get
            {
                return this.SoftwareIdField;
            }
            set
            {
                this.SoftwareIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoNodoId
        {
            get
            {
                return this.TipoNodoIdField;
            }
            set
            {
                this.TipoNodoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion
        {
            get
            {
                return this.UbicacionField;
            }
            set
            {
                this.UbicacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Software", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    public partial class Software : object
    {
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private ServiceReference.Empresa EmpresaField;
        
        private int EmpresaIdField;
        
        private string NombreField;
        
        private int SoftwareIdField;
        
        private string UbicacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference.Empresa Empresa
        {
            get
            {
                return this.EmpresaField;
            }
            set
            {
                this.EmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaId
        {
            get
            {
                return this.EmpresaIdField;
            }
            set
            {
                this.EmpresaIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoftwareId
        {
            get
            {
                return this.SoftwareIdField;
            }
            set
            {
                this.SoftwareIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion
        {
            get
            {
                return this.UbicacionField;
            }
            set
            {
                this.UbicacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/Filasur.AppCorp.Entities")]
    public partial class Rol : object
    {
        
        private string AbreviaturaField;
        
        private string DescripcionField;
        
        private string NombreField;
        
        private int RolIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Abreviatura
        {
            get
            {
                return this.AbreviaturaField;
            }
            set
            {
                this.AbreviaturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId
        {
            get
            {
                return this.RolIdField;
            }
            set
            {
                this.RolIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ISoftEmpAcceso")]
    public interface ISoftEmpAcceso
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencial", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencialResponse")]
        ServiceReference.Credencial ObtenerCredencial(string p_Usuario, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencial", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerCredencialResponse")]
        System.Threading.Tasks.Task<ServiceReference.Credencial> ObtenerCredencialAsync(string p_Usuario, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ValidaAcceso", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ValidaAccesoResponse")]
        ServiceReference.Credencial ValidaAcceso(string p_Usuario, string p_Clave, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ValidaAcceso", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ValidaAccesoResponse")]
        System.Threading.Tasks.Task<ServiceReference.Credencial> ValidaAccesoAsync(string p_Usuario, string p_Clave, bool p_UsaERP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerNodos", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerNodosResponse")]
        ServiceReference.Nodo[] ObtenerNodos(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerNodos", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerNodosResponse")]
        System.Threading.Tasks.Task<ServiceReference.Nodo[]> ObtenerNodosAsync(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerRol", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerRolResponse")]
        ServiceReference.Rol ObtenerRol(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/ObtenerRol", ReplyAction="http://tempuri.org/ISoftEmpAcceso/ObtenerRolResponse")]
        System.Threading.Tasks.Task<ServiceReference.Rol> ObtenerRolAsync(string p_CodApp, string p_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/CambiarPassword", ReplyAction="http://tempuri.org/ISoftEmpAcceso/CambiarPasswordResponse")]
        int CambiarPassword(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoftEmpAcceso/CambiarPassword", ReplyAction="http://tempuri.org/ISoftEmpAcceso/CambiarPasswordResponse")]
        System.Threading.Tasks.Task<int> CambiarPasswordAsync(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ISoftEmpAccesoChannel : ServiceReference.ISoftEmpAcceso, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SoftEmpAccesoClient : System.ServiceModel.ClientBase<ServiceReference.ISoftEmpAcceso>, ServiceReference.ISoftEmpAcceso
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SoftEmpAccesoClient(EndpointConfiguration endpointConfiguration) : 
                base(SoftEmpAccesoClient.GetBindingForEndpoint(endpointConfiguration), SoftEmpAccesoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoftEmpAccesoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SoftEmpAccesoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoftEmpAccesoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SoftEmpAccesoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SoftEmpAccesoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference.Credencial ObtenerCredencial(string p_Usuario, bool p_UsaERP)
        {
            return base.Channel.ObtenerCredencial(p_Usuario, p_UsaERP);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Credencial> ObtenerCredencialAsync(string p_Usuario, bool p_UsaERP)
        {
            return base.Channel.ObtenerCredencialAsync(p_Usuario, p_UsaERP);
        }
        
        public ServiceReference.Credencial ValidaAcceso(string p_Usuario, string p_Clave, bool p_UsaERP)
        {
            return base.Channel.ValidaAcceso(p_Usuario, p_Clave, p_UsaERP);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Credencial> ValidaAccesoAsync(string p_Usuario, string p_Clave, bool p_UsaERP)
        {
            return base.Channel.ValidaAccesoAsync(p_Usuario, p_Clave, p_UsaERP);
        }
        
        public ServiceReference.Nodo[] ObtenerNodos(string p_CodApp, string p_Usuario)
        {
            return base.Channel.ObtenerNodos(p_CodApp, p_Usuario);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Nodo[]> ObtenerNodosAsync(string p_CodApp, string p_Usuario)
        {
            return base.Channel.ObtenerNodosAsync(p_CodApp, p_Usuario);
        }
        
        public ServiceReference.Rol ObtenerRol(string p_CodApp, string p_Usuario)
        {
            return base.Channel.ObtenerRol(p_CodApp, p_Usuario);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.Rol> ObtenerRolAsync(string p_CodApp, string p_Usuario)
        {
            return base.Channel.ObtenerRolAsync(p_CodApp, p_Usuario);
        }
        
        public int CambiarPassword(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva)
        {
            return base.Channel.CambiarPassword(p_CredencialId, p_ClaveAnterior, p_ClaveNueva);
        }
        
        public System.Threading.Tasks.Task<int> CambiarPasswordAsync(string p_CredencialId, string p_ClaveAnterior, string p_ClaveNueva)
        {
            return base.Channel.CambiarPasswordAsync(p_CredencialId, p_ClaveAnterior, p_ClaveNueva);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISoftEmpAcceso))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISoftEmpAcceso))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISoftEmpAcceso))
            {
                return new System.ServiceModel.EndpointAddress("http://ik-seg-api.azurewebsites.net/SoftEmpAcceso.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISoftEmpAcceso))
            {
                return new System.ServiceModel.EndpointAddress("https://ik-seg-api.azurewebsites.net/SoftEmpAcceso.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISoftEmpAcceso,
            
            BasicHttpsBinding_ISoftEmpAcceso,
        }
    }
}
